### PR TITLE
Assign cosMap as undefined variables in strict mode (and ES6) throw errors

### PR DESCRIPTION
**Pull request by 2xAA**

### CODE REVIEW

**Comment by hughrawlinson** [comment]
:+1:

**Comment by avroshk** [comment]
Can this please me merged? Thanks.

**Comment by 2xAA** [comment]
Bump!

**Comment by 2xAA** [comment]
Bump?

**Comment by joshjung** [comment]
Hey guys, apologies about this, was not seeing the notifications on this and was waiting for someone at Vail Systems to take over :D I still have access to this repository so I'll go ahead and merge this.

**Comment by 2xAA** [comment]
Brilliant! Thanks, Josh!

**Pull request merged**
